DirectoryPath: public
IgnoreAltMissing: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true # At least until the following is fixed: https://github.com/gohugoio/hugo/issues/9149
CheckDoctype: false # Sadly, this is false only because of `google*.html`
IgnoreURLs:
  - ^https?://localhost
  - http://bit\.ly/gRPC18survey # survey is closed and DNE
  - https://(www.)?envoyproxy.io # valid link but flakey (https://github.com/envoyproxy/envoyproxy.github.io/issues/193)
IgnoreInternalURLs:
  - ../api
  - /docs/languages/cpp/api/
  - /docs/languages/csharp/api/
  - /docs/languages/csharp/daily-builds/
  - /docs/languages/dart/api/
  - /docs/languages/go/api/
  - /docs/languages/java/api/
  - /docs/languages/kotlin/api
  - /docs/languages/kotlin/api/
  - /docs/languages/node/api/
  - /docs/languages/objective-c/api/
  - /docs/languages/php/api/
  - /docs/languages/php/daily-builds/
  - /docs/languages/python/api/
  - /docs/languages/python/daily-builds/
  - /docs/languages/ruby/api/
  - /docs/languages/ruby/daily-builds/
  - /docs/platforms/android/java/api/
  - /docs/platforms/android/kotlin/api/
  - /grpc/cpp/classgrpc_1_1_completion_queue.html
  - /grpc/python/_modules/grpc.html#Server
  - /grpc/python/grpc.html?#grpc.StreamStreamMultiCallable
  - /grpc/python/grpc.html?#grpc.StreamUnaryMultiCallable
  - /grpc/python/grpc.html?#grpc.UnaryStreamMultiCallable
  - /grpc/python/grpc.html?#grpc.UnaryUnaryMultiCallable
  - api/
  - daily-builds
