DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
CheckDoctype: false # Sadly, this is false only because of `google*.html`
IgnoreURLs:
  - "^https?://localhost.*"
IgnoreInternalURLs:
  - /docs/languages/csharp/daily-builds/
  - /docs/languages/php/daily-builds/
  - /docs/languages/python/daily-builds/
  - /docs/languages/ruby/daily-builds/
  - /grpc/cpp/classgrpc_1_1_completion_queue.html
  - /grpc/python/_modules/grpc.html#Server
  - /grpc/python/grpc.html?#grpc.StreamStreamMultiCallable
  - /grpc/python/grpc.html?#grpc.StreamUnaryMultiCallable
  - /grpc/python/grpc.html?#grpc.UnaryStreamMultiCallable
  - /grpc/python/grpc.html?#grpc.UnaryUnaryMultiCallable
  - api
  - daily-builds
